# Generated by Django 4.1 on 2022-08-17 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JunJob', '0002_company_owner_alter_company_logo_and_more'),
    ]
