# Generated by Django 4.1 on 2022-11-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JunJob', '0011_application_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='vacancy',
        ),
    ]
