# Generated by Django 4.1 on 2022-11-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JunJob', '0012_remove_answer_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_viewed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
