# Generated by Django 4.1 on 2022-11-21 15:04

import JunJob.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JunJob', '0013_application_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatar.jpg', upload_to='avatars',
                                    validators=[JunJob.models.Profile.validate_image]),
        ),
    ]
